# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musorg.ui'
#
# Created: Fri Mar 20 12:21:25 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 682)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.main_tab = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab.sizePolicy().hasHeightForWidth())
        self.main_tab.setSizePolicy(sizePolicy)
        self.main_tab.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.main_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_tab.setTabShape(QtGui.QTabWidget.Rounded)
        self.main_tab.setObjectName("main_tab")
        self.tab_downloader = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_downloader.sizePolicy().hasHeightForWidth())
        self.tab_downloader.setSizePolicy(sizePolicy)
        self.tab_downloader.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_downloader.setObjectName("tab_downloader")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_downloader)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_search = QtGui.QPushButton(self.tab_downloader)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.lne_search = QtGui.QLineEdit(self.tab_downloader)
        self.lne_search.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lne_search.setObjectName("lne_search")
        self.horizontalLayout.addWidget(self.lne_search)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label = QtGui.QLabel(self.tab_downloader)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.trw_results = QtGui.QTreeView(self.tab_downloader)
        self.trw_results.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.trw_results.setDragEnabled(True)
        self.trw_results.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.trw_results.setObjectName("trw_results")
        self.horizontalLayout_3.addWidget(self.trw_results)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_2 = QtGui.QLabel(self.tab_downloader)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.trw_downloads = QtGui.QTreeView(self.tab_downloader)
        self.trw_downloads.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.trw_downloads.setDragEnabled(True)
        self.trw_downloads.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.trw_downloads.setObjectName("trw_downloads")
        self.horizontalLayout_4.addWidget(self.trw_downloads)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/downloader.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_tab.addTab(self.tab_downloader, icon1, "")
        self.tab_organizer = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_organizer.sizePolicy().hasHeightForWidth())
        self.tab_organizer.setSizePolicy(sizePolicy)
        self.tab_organizer.setObjectName("tab_organizer")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.tab_organizer)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtGui.QTabWidget(self.tab_organizer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trw_albums = QtGui.QTreeView(self.tab)
        self.trw_albums.setHeaderHidden(True)
        self.trw_albums.setObjectName("trw_albums")
        self.verticalLayout.addWidget(self.trw_albums)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.toolButton_8 = QtGui.QToolButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_8.setIcon(icon2)
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_9.addWidget(self.toolButton_8)
        self.tb_import_albums = QtGui.QToolButton(self.tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_import_albums.setIcon(icon3)
        self.tb_import_albums.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.tb_import_albums.setArrowType(QtCore.Qt.NoArrow)
        self.tb_import_albums.setObjectName("tb_import_albums")
        self.horizontalLayout_9.addWidget(self.tb_import_albums)
        self.toolButton_2 = QtGui.QToolButton(self.tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_9.addWidget(self.toolButton_2)
        self.toolButton = QtGui.QToolButton(self.tab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon5)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_9.addWidget(self.toolButton)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.pb_reload = QtGui.QProgressBar(self.tab)
        self.pb_reload.setEnabled(True)
        self.pb_reload.setProperty("value", QtCore.QVariant(0))
        self.pb_reload.setObjectName("pb_reload")
        self.horizontalLayout_10.addWidget(self.pb_reload)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.trw_favourites = QtGui.QTreeView(self.tab_2)
        self.trw_favourites.setObjectName("trw_favourites")
        self.verticalLayout_6.addWidget(self.trw_favourites)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolButton_4 = QtGui.QToolButton(self.tab_2)
        self.toolButton_4.setIcon(icon3)
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_2.addWidget(self.toolButton_4)
        self.toolButton_5 = QtGui.QToolButton(self.tab_2)
        self.toolButton_5.setIcon(icon4)
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_2.addWidget(self.toolButton_5)
        self.toolButton_7 = QtGui.QToolButton(self.tab_2)
        self.toolButton_7.setIcon(icon5)
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_2.addWidget(self.toolButton_7)
        self.toolButton_6 = QtGui.QToolButton(self.tab_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/package.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_6.setIcon(icon6)
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_2.addWidget(self.toolButton_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_8.addWidget(self.tabWidget)
        self.trw_tracks = QtGui.QTreeView(self.tab_organizer)
        self.trw_tracks.setObjectName("trw_tracks")
        self.horizontalLayout_8.addWidget(self.trw_tracks)
        self.main_tab.addTab(self.tab_organizer, "")
        self.tab_pref = QtGui.QWidget()
        self.tab_pref.setObjectName("tab_pref")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_pref)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_pref)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setRowWrapPolicy(QtGui.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lne_download_dir = QtGui.QLineEdit(self.groupBox_2)
        self.lne_download_dir.setObjectName("lne_download_dir")
        self.horizontalLayout_6.addWidget(self.lne_download_dir)
        self.btn_browse_down_dir = QtGui.QPushButton(self.groupBox_2)
        self.btn_browse_down_dir.setObjectName("btn_browse_down_dir")
        self.horizontalLayout_6.addWidget(self.btn_browse_down_dir)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinBox = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.spinBox.setAccelerated(True)
        self.spinBox.setMinimum(-1)
        self.spinBox.setProperty("value", QtCore.QVariant(-1))
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cb_engines = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_engines.sizePolicy().hasHeightForWidth())
        self.cb_engines.setSizePolicy(sizePolicy)
        self.cb_engines.setMinimumSize(QtCore.QSize(200, 0))
        self.cb_engines.setEditable(False)
        self.cb_engines.setObjectName("cb_engines")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cb_engines)
        self.horizontalLayout_5.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tab_pref)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.main_tab.addTab(self.tab_pref, "")
        self.horizontalLayout_7.addWidget(self.main_tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 23))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionSave_Preferences = QtGui.QAction(MainWindow)
        self.actionSave_Preferences.setIcon(icon)
        self.actionSave_Preferences.setObjectName("actionSave_Preferences")
        self.actionPause_Download = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause_Download.setIcon(icon7)
        self.actionPause_Download.setObjectName("actionPause_Download")
        self.actionResume_Download = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/player_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResume_Download.setIcon(icon8)
        self.actionResume_Download.setObjectName("actionResume_Download")
        self.actionStart_Download = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart_Download.setIcon(icon9)
        self.actionStart_Download.setObjectName("actionStart_Download")
        self.actionRemove_Download = QtGui.QAction(MainWindow)
        self.actionRemove_Download.setIcon(icon4)
        self.actionRemove_Download.setObjectName("actionRemove_Download")
        self.actionCorrect_Encodings = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/encoding.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCorrect_Encodings.setIcon(icon10)
        self.actionCorrect_Encodings.setObjectName("actionCorrect_Encodings")
        self.actionReload_Collection = QtGui.QAction(MainWindow)
        self.actionReload_Collection.setIcon(icon2)
        self.actionReload_Collection.setObjectName("actionReload_Collection")
        self.actionAuto_Organize = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/organize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAuto_Organize.setIcon(icon11)
        self.actionAuto_Organize.setObjectName("actionAuto_Organize")
        self.actionImport_Files = QtGui.QAction(MainWindow)
        self.actionImport_Files.setIcon(icon3)
        self.actionImport_Files.setObjectName("actionImport_Files")
        self.actionImport_Directory = QtGui.QAction(MainWindow)
        self.actionImport_Directory.setIcon(icon3)
        self.actionImport_Directory.setObjectName("actionImport_Directory")
        self.menubar.addAction(self.menu_File.menuAction())
        self.toolBar.addAction(self.actionStart_Download)
        self.toolBar.addAction(self.actionRemove_Download)
        self.toolBar.addAction(self.actionResume_Download)
        self.toolBar.addAction(self.actionPause_Download)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionReload_Collection)
        self.toolBar.addAction(self.actionCorrect_Encodings)
        self.toolBar.addAction(self.actionAuto_Organize)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave_Preferences)

        self.retranslateUi(MainWindow)
        self.main_tab.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_search.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Search Results:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Downloads:", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_downloader), QtGui.QApplication.translate("MainWindow", "Downloader", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_8.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_import_albums.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_2.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_4.setText(QtGui.QApplication.translate("MainWindow", "Add Favourite", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_5.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_7.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_6.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Favourites", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_organizer), QtGui.QApplication.translate("MainWindow", "Organizer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Downloader Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Download Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_browse_down_dir.setText(QtGui.QApplication.translate("MainWindow", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Maximum Download:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Search Engine:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Organizer Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab.setTabText(self.main_tab.indexOf(self.tab_pref), QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Preferences.setText(QtGui.QApplication.translate("MainWindow", "Save Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPause_Download.setText(QtGui.QApplication.translate("MainWindow", "Pause Download", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResume_Download.setText(QtGui.QApplication.translate("MainWindow", "Resume Download", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Download.setText(QtGui.QApplication.translate("MainWindow", "Start Download", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemove_Download.setText(QtGui.QApplication.translate("MainWindow", "Remove Download", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCorrect_Encodings.setText(QtGui.QApplication.translate("MainWindow", "Correct Encodings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReload_Collection.setText(QtGui.QApplication.translate("MainWindow", "Reload Collection", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuto_Organize.setText(QtGui.QApplication.translate("MainWindow", "Auto-Organize", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Files.setText(QtGui.QApplication.translate("MainWindow", "Import Files", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Directory.setText(QtGui.QApplication.translate("MainWindow", "Import Directory", None, QtGui.QApplication.UnicodeUTF8))

import musorg_rc
