#!/usr/bin/env python
# -*- coding: utf-8 -*-

# start_downloader
# author: rshen
# date: 2009-03-21

import sys
import os
from PyQt4.QtGui import QApplication
from PyQt4.QtCore import QFile
import musorg as app
from musorg.config import Configuration

# Load the configuration file first
pref_dir = os.path.expanduser("~/.musorg")
if not os.path.exists(pref_dir):
    os.makedirs(pref_dir)

pref_file = os.path.expanduser("~/.musorg/musorg.cfg")
if not os.path.exists(pref_file):
    def_file = QFile(":/configuration/conf/musorg.cfg")
    def_file.copy(pref_file)
    QFile.setPermissions(pref_file, QFile.ReadUser | QFile.WriteUser)

config = Configuration(pref_file)
app.main(config)
