# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_album.ui'
#
# Created: Wed Mar 25 17:38:39 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EditDialog(object):
    def setupUi(self, EditDialog):
        EditDialog.setObjectName("EditDialog")
        EditDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        EditDialog.resize(562, 240)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditDialog.sizePolicy().hasHeightForWidth())
        EditDialog.setSizePolicy(sizePolicy)
        EditDialog.setMinimumSize(QtCore.QSize(562, 240))
        EditDialog.setMaximumSize(QtCore.QSize(562, 240))
        EditDialog.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(EditDialog)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lb_cover = QtGui.QLabel(EditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_cover.sizePolicy().hasHeightForWidth())
        self.lb_cover.setSizePolicy(sizePolicy)
        self.lb_cover.setMinimumSize(QtCore.QSize(128, 128))
        self.lb_cover.setMaximumSize(QtCore.QSize(128, 128))
        self.lb_cover.setPixmap(QtGui.QPixmap(":/icons/icons/empty_cd.png"))
        self.lb_cover.setObjectName("lb_cover")
        self.verticalLayout_2.addWidget(self.lb_cover)
        self.btn_change_cover = QtGui.QPushButton(EditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_change_cover.sizePolicy().hasHeightForWidth())
        self.btn_change_cover.setSizePolicy(sizePolicy)
        self.btn_change_cover.setMinimumSize(QtCore.QSize(128, 0))
        self.btn_change_cover.setMaximumSize(QtCore.QSize(128, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_change_cover.setIcon(icon)
        self.btn_change_cover.setObjectName("btn_change_cover")
        self.verticalLayout_2.addWidget(self.btn_change_cover)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(EditDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lne_name = QtGui.QLineEdit(EditDialog)
        self.lne_name.setObjectName("lne_name")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lne_name)
        self.label_3 = QtGui.QLabel(EditDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_rating = QtGui.QComboBox(EditDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_rating.sizePolicy().hasHeightForWidth())
        self.cb_rating.setSizePolicy(sizePolicy)
        self.cb_rating.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cb_rating.setObjectName("cb_rating")
        self.horizontalLayout_2.addWidget(self.cb_rating)
        self.frame = QtGui.QFrame(EditDialog)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.hl_stars = QtGui.QHBoxLayout()
        self.hl_stars.setObjectName("hl_stars")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.hl_stars.addWidget(self.label)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.hl_stars.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.hl_stars.addWidget(self.label_7)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.hl_stars.addWidget(self.label_5)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.hl_stars.addWidget(self.label_8)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl_stars.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.hl_stars)
        self.horizontalLayout_2.addWidget(self.frame)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(EditDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cb_artist = QtGui.QComboBox(EditDialog)
        self.cb_artist.setObjectName("cb_artist")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cb_artist)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtGui.QDialogButtonBox(EditDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EditDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), EditDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), EditDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EditDialog)

    def retranslateUi(self, EditDialog):
        EditDialog.setWindowTitle(QtGui.QApplication.translate("EditDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_change_cover.setText(QtGui.QApplication.translate("EditDialog", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EditDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EditDialog", "Rating", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EditDialog", "Artist", None, QtGui.QApplication.UnicodeUTF8))

import musorg_rc
