# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'organizer.ui'
#
# Created: Mon Mar 23 13:32:42 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Organizer(object):
    def setupUi(self, Organizer):
        Organizer.setObjectName("Organizer")
        Organizer.resize(830, 590)
        self.verticalLayout = QtGui.QVBoxLayout(Organizer)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtGui.QSplitter(Organizer)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(580, 0))
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(200, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.trw_albums = QtGui.QTreeView(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trw_albums.sizePolicy().hasHeightForWidth())
        self.trw_albums.setSizePolicy(sizePolicy)
        self.trw_albums.setHeaderHidden(True)
        self.trw_albums.setObjectName("trw_albums")
        self.verticalLayout_4.addWidget(self.trw_albums)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tb_reload_collection = QtGui.QToolButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_reload_collection.setIcon(icon)
        self.tb_reload_collection.setObjectName("tb_reload_collection")
        self.horizontalLayout.addWidget(self.tb_reload_collection)
        self.tb_import_albums = QtGui.QToolButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_import_albums.setIcon(icon1)
        self.tb_import_albums.setPopupMode(QtGui.QToolButton.MenuButtonPopup)
        self.tb_import_albums.setArrowType(QtCore.Qt.NoArrow)
        self.tb_import_albums.setObjectName("tb_import_albums")
        self.horizontalLayout.addWidget(self.tb_import_albums)
        self.tb_remove_albums = QtGui.QToolButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_remove_albums.setIcon(icon2)
        self.tb_remove_albums.setObjectName("tb_remove_albums")
        self.horizontalLayout.addWidget(self.tb_remove_albums)
        self.tb_edit_album = QtGui.QToolButton(self.tab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_edit_album.setIcon(icon3)
        self.tb_edit_album.setObjectName("tb_edit_album")
        self.horizontalLayout.addWidget(self.tb_edit_album)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_reload = QtGui.QProgressBar(self.tab)
        self.pb_reload.setProperty("value", QtCore.QVariant(0))
        self.pb_reload.setObjectName("pb_reload")
        self.horizontalLayout.addWidget(self.pb_reload)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.trw_tracks = QtGui.QTreeView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trw_tracks.sizePolicy().hasHeightForWidth())
        self.trw_tracks.setSizePolicy(sizePolicy)
        self.trw_tracks.setObjectName("trw_tracks")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Organizer)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Organizer)

    def retranslateUi(self, Organizer):
        Organizer.setWindowTitle(QtGui.QApplication.translate("Organizer", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_reload_collection.setText(QtGui.QApplication.translate("Organizer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_import_albums.setText(QtGui.QApplication.translate("Organizer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_remove_albums.setText(QtGui.QApplication.translate("Organizer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_edit_album.setText(QtGui.QApplication.translate("Organizer", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Organizer", "Albums", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Organizer", "Favourites", None, QtGui.QApplication.UnicodeUTF8))

import musorg_rc
